apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chat-gateway-ingress
  namespace: default
spec:
  routes:
    - kind: Rule
      match: Host(`chat-gateway.veld.dev`)
      services:
        - name: chat-gateway
          namespace: default
          port: 1234
